### ISSUE TITLE
Updated for Gen 8?

### ISSUE THREAD

**Issue by ThomasHineXYZ** [forsureitsme/PokemonTeamSyntax#6]
I was wondering if there is any plans to update this for Pokemon Sword and Shield with its new additions?

**Comment by forsureitsme** [comment]
A bit late, but I'm looking into it.

**Comment by forsureitsme** [comment]
Resolved in [latest release](https://github.com/forsureitsme/PokemonTeamSyntax/releases/tag/3.0.0).

**Comment by ThomasHineXYZ** [comment]
Sweet, thank you!
