### ISSUE TITLE
Pokemon suggestions showing up in other source code files

### ISSUE THREAD

**Issue by ThomasHineXYZ** [forsureitsme/PokemonTeamSyntax#7]
Looking around at the repo, this line should probably be changed:

https://github.com/forsureitsme/PokemonTeamSyntax/blob/af684c6160e92cf17f89f69a3f336d1800c8e24a/PokemonTeamSyntax.sublime-completions#L2

To this `source.pktm`. That way it only gets autocompleted in this syntax's autocomplete.

**Comment by forsureitsme** [comment]
Fixed in [3.0.1](https://github.com/forsureitsme/PokemonTeamSyntax/releases/tag/3.0.1)

**Comment by ThomasHineXYZ** [comment]
Yay, thank you. No more Pokemon suggestions in my PHP files :D
